# Generated by Django 5.0.2 on 2024-03-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Quotes',
        ),
    ]
