# Generated by Django 5.0.2 on 2024-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('main_goal', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
